"""add_application_tracking_columns

Revision ID: 475af1c1f7b0
Revises: 786557edfb46
Create Date: 2026-05-23 20:32:56.830140

"""
from alembic import op
import sqlalchemy as sa


revision = '475af1c1f7b0'
down_revision = '786557edfb46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_status', sa.Enum('applied', 'under_review', 'shortlisted', 'interview_scheduled', 'rejected', 'accepted', name='applicationstatus'), server_default='applied', nullable=False))
        batch_op.add_column(sa.Column('shortlisted', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('recruiter_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('meeting_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('interview_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('interview_instructions')
        batch_op.drop_column('meeting_link')
        batch_op.drop_column('interview_date')
        batch_op.drop_column('recruiter_notes')
        batch_op.drop_column('shortlisted')
        batch_op.drop_column('application_status')

    # ### end Alembic commands ###
